### ISSUE TITLE
retsnoop: update sidecar dependencies

### ISSUE THREAD

**Issue by michel-slm** [anakryiko/retsnoop#54]
`blazesym` is getting packaged in distributions, and it depends on `addr2line` 0.21.0 and `gimli` 0.28

https://crates.io/crates/blazesym/0.2.0-alpha.8/dependencies

There are some API changes with some functions now marked private that means retsnoop cannot be rebuilt against these versions, and it would be very useful to be able to build retsnoop (either for the upcoming Fedora 40 mass rebuild in a few months, or if a new version is released) without having to package compatibility versions of these two dependencies

**Comment by danielocfb** [comment]
Addressed by https://github.com/anakryiko/retsnoop/pull/55 ?
