### ISSUE TITLE
Consult one question about cards_found

### ISSUE THREAD

**Issue by mzhan017** [anakryiko/retsnoop#7]
Hello,
I capture one trace with this kind of:
                             entry_SYSCALL_64_after_hwframe+0x65
                             do_syscall_64+0x5b
                             __x64_sys_sendto+0x24
                             __sys_sendto+0xee
           27us [-EAGAIN]    sock_sendmsg+0x5
                             cards_found.85860+0x1a4
                             sock_sendmsg+0x3e
           24us [-EAGAIN]    tcp_sendmsg+0x5
                             cards_found.85860+0x1ac
                             tcp_sendmsg+0x27
            3us [-EAGAIN]    tcp_sendmsg_locked+0x5
                             cards_found.85860+0x1c6
                             cards_found.85860+0x125
                             cards_found.85860+0x1fb
                             cards_found.85860+0x19e
                             cards_found.85860+0x19e

But there is something that I cannot find from vmlinux :(
How to check the cards_found.85860?

Thanks,
Mark

**Comment by mzhan017** [comment]
# strings ./kernel/drivers/net/ethernet/intel/e1000e/e1000e.ko | grep card
cards_found.85860

**Comment by anakryiko** [comment]
As you can see captured stack trace has 000000000000002c entries in it, which retsnoop is symbolizing relative to closes (non-function) symbol cards_found.85860. Which is wrong and confusing, I think it would be better to just print out unsymbolized 0x1f2 (or whatever the original value was) in this case.

But as to why the stack trace is corrupted -- no idea, it's tracing, there is always something that might not work.
