### ISSUE TITLE
How retsnoop trace a linux kernel module with -S -T?

### ISSUE THREAD

**Issue by andyzhanged** [anakryiko/retsnoop#88]
I want to trace a function from a linux kernel module, but it failed to print subfunction call stack, is my flag '-a' wrong?

My cmd is `retsnoop -e 'itr_lib_ioctl' -a ':/opt/sw_home/sdk/ixdriver/kmd/itr/kmdlib/*.c' -a ':itr/kmdlib/*.c' -S -T` and output 

```
14:38:09.594498 -> 14:38:09.594634 TID/PID 71216/71215 (vectorAdd/vectorAdd):

FUNCTION CALLS    RESULT   DURATION
---------------   ------  ---------
↔ itr_lib_ioctl   [0]     132.102us


14:38:09.594636 -> 14:38:09.604627 TID/PID 71216/71215 (vectorAdd/vectorAdd):

FUNCTION CALLS    RESULT    DURATION
---------------   ------  ----------
↔ itr_lib_ioctl   [0]     9989.368us
```

**Comment by anakryiko** [comment]
you can specify `-v --dry-run` to see all the functions that retsnoop discovers. I think for kernel modules source code location based search (like what you do here with `-a ':/opt/...'` doesn't work.

But for kernel modules it's actually really easy to filter functions by name and module name. Try `-a '*[my_module]'`, it should find everything traceable from `my_module` kernel module.

**Comment by andyzhanged** [comment]
Thanks， `-a '*[my_module]'` can works.
